name: 'brisbane_customer_demand'
version: '1.0.0'
config-version: 2

profile: 'brisbane_customer_demand'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  brisbane_customer_demand:
    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: table

    marts:
      +schema: marts
      +materialized: table
